print("Hello world")
print("My favourite food is chicken rice")
print("My birthday is on 24 October 2013")
print("My name is Elijah")
print("I am 11 years old")
print("I attend St. Joseph's Institution Junior")